# Generated by Django 5.1.6 on 2025-02-08 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade_level', models.CharField(choices=[('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12')], max_length=2)),
                ('status', models.CharField(choices=[('ac', 'Active'), ('in', 'Inactive'), ('pd', 'Pending')], max_length=2)),
                ('schedule', models.CharField(choices=[('mr', 'Morning Session'), ('af', 'Afternoon Session'), ('ev', 'Evening Session')], max_length=2)),
                ('academic_year', models.CharField(max_length=30)),
                ('max_students', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('subjects', models.ManyToManyField(related_name='groups', to='subjects.subject')),
                ('teacher', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='teachers.teacher')),
            ],
        ),
    ]
