# Generated by Django 5.1.6 on 2025-02-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('head_department', models.CharField(blank=True, choices=[('js', 'Dr. Jane Smith'), ('jd', 'Dr. John Doe'), ('sj', 'Prof. Sarah Johnson')], max_length=2)),
                ('location', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('status', models.CharField(choices=[('ac', 'Active'), ('in', 'Inactive'), ('pd', 'Pending')], default='ac', max_length=2)),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
